version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - turnos-net

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    volumes:
      - ./docker/activemq/activemq.xml:/opt/activemq/conf/activemq.xml
      - ./docker/activemq/credentials.properties:/opt/activemq/conf/credentials.properties
    ports:
      - "61616:61616"
      - "8161:8161"
      - "61613:61613"
    networks:
      - turnos-net

  servicio-cliente:
    image: youruser/servicio-cliente:latest
    container_name: servicio-cliente
    env_file: ./env/servicio-cliente.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - activemq
    networks:
      - turnos-net

  servicio-asesor:
    image: youruser/servicio-asesor:latest
    container_name: servicio-asesor
    env_file: ./env/servicio-asesor.env
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - activemq
    networks:
      - turnos-net

networks:
  turnos-net:
    driver: bridge
