version: "3.9"

services:
  servicio-cliente:
    build: ./servicio-cliente
    container_name: servicio-cliente
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    depends_on:
      - activemq
      - redis
    volumes:
      - ./servicio-cliente:/app
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"

  servicio-asesor:
    build: ./servicio-asesor
    container_name: servicio-asesor
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
    depends_on:
      - activemq
      - redis
    volumes:
      - ./servicio-asesor:/app
    command: bash -c "bundle exec rails s -p 3001 -b '0.0.0.0'"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"
