services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"

  servicio-cliente:
    build:
      context: ../servicio-cliente
      dockerfile: Dockerfile
    container_name: servicio-cliente
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - activemq
    environment:
      REDIS_URL: redis://redis:6379/0
      AMQ_STOMP_URL: stomp://activemq:61613
      AMQ_USER: admin
      AMQ_PASSWORD: admin
      SECRET_KEY_BASE: "dummysecretforcontainer"
      PORT: 3000

  servicio-asesor:
    build:
      context: ../servicio-asesor
      dockerfile: Dockerfile
    container_name: servicio-asesor
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - activemq
    environment:
      REDIS_URL: redis://redis:6379/0
      AMQ_STOMP_URL: stomp://activemq:61613
      AMQ_USER: admin
      AMQ_PASSWORD: admin
      SECRET_KEY_BASE: "dummysecretforcontainer"
      PORT: 3001

networks:
  default:
    name: turnos-net
