version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"

  servicio-cliente:
    build: ./servicio-cliente
    container_name: servicio-cliente
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - activemq

  servicio-asesor:
    build: ./servicio-asesor
    container_name: servicio-asesor
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - activemq
